name: docker_base
on:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'tools/docker/base/**'
    branches:
      - develop

jobs:
  docker_base:
    runs-on: ubuntu-20.04
    # We shouldn't run it on forks.
    if: github.repository_owner == 'ockam-network'
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ockam-network/ockam/builder_base

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: tools/docker/base
          push: true
          tags: ghcr.io/ockam-network/ockam/builder_base:latest
